name: picky-backend-ci-cd

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          package: 'jdk'
          jdk-version: '17.0.12'

      - name: checkout
        uses: actions/checkout@main

      - name: create env and secure file
        run: |
          cd ./src/main/resources/properties
          touch jwt.yml
          echo "${{ secrets.JWT }}" >> jwt.yml
          touch mysql-prod.yml
          echo "${{ secrets.MYSQL_PROD }}" >> mysql-prod.yml
          touch mysql-local.yml
          echo "${{ secrets.MYSQL_LOCAL }}" >> mysql-local.yml
          touch redis.yml
          echo "${{ secrets.REDIS }}" >> redis.yml
          touch naver.yml
          echo "${{ secrets.NAVER }}" >> naver.yml
          touch frontend.yml
          echo "${{ secrets.FRONTEND }}" >> frontend.yml
          

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Image build and push
        run: |
          sudo docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          sudo docker build -t ${{ secrets.DOCKER_USERNAME }}/picky-backend:latest . 
          sudo docker push ${{ secrets.DOCKER_USERNAME }}/picky-backend:latest

      - name: docker run
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          # passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            sudo docker stop picky-backend
            sudo docker rm picky-backend
            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/picky-backend:latest
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/picky-backend:latest
            sudo docker run -d -p 8080:8080 --name picky-backend -e SPRING_PROFILES_ACTIVE=aws ${{ secrets.DOCKER_USERNAME }}/picky-backend:latest
